In [1]:
import pandas as pd
import numpy as np

Import data

In [2]:
original_data = pd.read_csv('NS_services-2023.csv')

In [3]:
len(original_data)

21239393

Data exploration

In [ ]:
original_data.head(100)

,Service:RDT-ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled
0,10367702,2023-01-01,Intercity,NS,1410,False,False,3,93067918,RTD,Rotterdam Centraal,NaN,NaN,NaN,2023-01-01T02:00:00+01:00,1.0,False
1,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067919,DT,Delft,2023-01-01T02:13:00+01:00,0.0,False,2023-01-01T02:13:00+01:00,0.0,False
2,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067920,GV,Den Haag HS,2023-01-01T02:21:00+01:00,0.0,False,2023-01-01T02:22:00+01:00,0.0,False
3,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067921,LEDN,Leiden Centraal,2023-01-01T02:35:00+01:00,0.0,False,2023-01-01T02:40:00+01:00,0.0,False
4,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067922,SHL,Schiphol Airport,2023-01-01T02:56:00+01:00,0.0,False,2023-01-01T03:03:00+01:00,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10367711,2023-01-01,Sprinter,NS,5806,False,False,0,93068013,BRN,Baarn,2023-01-01T04:55:00+01:00,1.0,False,2023-01-01T04:55:00+01:00,0.0,False
96,10367711,2023-01-01,Sprinter,NS,5806,False,False,0,93068014,HVS,Hilversum,2023-01-01T05:01:00+01:00,0.0,False,2023-01-01T05:02:00+01:00,0.0,False
97,10367711,2023-01-01,Sprinter,NS,5806,False,False,0,93068015,HVSM,Hilversum Media Park,2023-01-01T05:04:00+01:00,0.0,False,2023-01-01T05:04:00+01:00,1.0,False
98,10367711,2023-01-01,Sprinter,NS,5806,False,False,0,93068016,BSMZ,Bussum Zuid,2023-01-01T05:08:00+01:00,0.0,False,2023-01-01T05:08:00+01:00,1.0,False
99,10367711,2023-01-01,Sprinter,NS,5806,False,False,0,93068017,NDB,Naarden-Bussum,2023-01-01T05:11:00+01:00,1.0,False,2023-01-01T05:11:00+01:00,2.0,False

In [5]:
original_data.describe()

,Service:RDT-ID,Service:Train number,Service:Maximum delay,Stop:RDT-ID,Stop:Arrival delay,Stop:Departure delay
count,2.123939e+07,2.123939e+07,2.123939e+07,2.123939e+07,1.889747e+07,1.889443e+07
mean,1.152188e+07,6.781269e+04,2.180872e-01,1.036925e+08,9.549407e-01,8.912648e-01
std,6.745719e+05,2.138766e+05,1.686290e+00,6.131356e+06,3.367316e+00,3.163841e+00
min,1.036770e+07,1.000000e+00,0.000000e+00,9.306792e+07,0.000000e+00,0.000000e+00
25%,1.093636e+07,4.343000e+03,0.000000e+00,9.838268e+07,0.000000e+00,0.000000e+00
50%,1.151608e+07,6.939000e+03,0.000000e+00,1.036925e+08,0.000000e+00,0.000000e+00
75%,1.210681e+07,3.074900e+04,0.000000e+00,1.090024e+08,1.000000e+00,1.000000e+00
max,1.270536e+07,9.921460e+05,1.443000e+03,1.144521e+08,1.443000e+03,1.443000e+03

In [6]:
original_data.describe(include = 'object')

,Service:Date,Service:Type,Service:Company,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure cancelled
count,21239393,21239393,21239393,21212213,21239393,18897468,18897468,18894430,18894430
unique,365,24,29,557,561,486905,2,487548,2
top,2023-04-19,Sprinter,NS,UT,Utrecht Centraal,2023-07-07T17:05:00+02:00,False,2023-01-27T16:45:00+01:00,False
freq,67354,9305246,13816273,431204,431204,85,17683702,96,17680799

In [7]:
original_data['Service:Company'].unique()

array(['NS', 'NS Int', 'Arriva', 'VIAS', 'NMBS', 'Eurobahn', 'R-net',
       'Blauwnet', 'Valleilijn', 'DB', 'Breng', 'EB', 'ns', 'noord',
       'keo', 'BN', 'ZLSM', '.', 'Eu Sleeper', 'breng', 'NSI', 'ABRN',
       'Qbuzz', 'Keolis', 'Ret', 'Rnet', 'connexxi', 'RRReis', 'GVB'],
      dtype=object)

What is ns? NSI?

In [8]:
ns_ = original_data[original_data['Service:Company'] == "ns"]
nsi_ = original_data[original_data['Service:Company'] == "NSI"]

In [9]:
ns_['Service:Type'].unique()

array(['Stopbus i.p.v. trein', 'Snelbus i.p.v. trein'], dtype=object)

In [10]:
nsi_['Service:Type'].unique()

array(['Snelbus ipv trein'], dtype=object)

What is NS Int?

In [11]:
NS_Int = original_data[original_data['Service:Company'] == "NS Int"]

In [12]:
NS_Int['Service:Type'].unique()

array(['Nightjet', 'Intercity direct', 'ICE International', 'Thalys',
       'Eurostar', 'Intercity', 'Int. Trein', 'Stopbus ipv trein'],
      dtype=object)

Nighjet is an OBB service. ICE International is from DB. Thalys and Eurostar are different operators too. I think the best is to focus only on NS trains, and to let NS Int aside

Let's filter, to keep only NS trains (NS, and NS Int)

In [13]:
data = original_data

In [14]:
operators = ['NS']
data = data[data['Service:Company'].isin(operators)]

In [15]:
data['Service:Company'].unique()

array(['NS'], dtype=object)

On this smaller data set, let's see how we can find the numbers of trains per day (and then month, and year)

<I> Let's try using the Service:RDT-ID</I>

* Info from rijdendetreinen.nl : This is the ID that Rijden de Treinen uses for this service. It has no useful meaning beyond uniquely identifying a single service on a single date.
Attention:
This ID will occur more than once in the CSV files because this ID is unique for each service. There is also a column Stop:RDT-ID with a unique ID for each stop.

In [16]:
data = data.rename(columns={"Service:RDT-ID" : "Service_ID"})

In [17]:
data[data.Service_ID == 10367702]

,Service_ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled
0,10367702,2023-01-01,Intercity,NS,1410,False,False,3,93067918,RTD,Rotterdam Centraal,NaN,NaN,NaN,2023-01-01T02:00:00+01:00,1.0,False
1,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067919,DT,Delft,2023-01-01T02:13:00+01:00,0.0,False,2023-01-01T02:13:00+01:00,0.0,False
2,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067920,GV,Den Haag HS,2023-01-01T02:21:00+01:00,0.0,False,2023-01-01T02:22:00+01:00,0.0,False
3,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067921,LEDN,Leiden Centraal,2023-01-01T02:35:00+01:00,0.0,False,2023-01-01T02:40:00+01:00,0.0,False
4,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067922,SHL,Schiphol Airport,2023-01-01T02:56:00+01:00,0.0,False,2023-01-01T03:03:00+01:00,0.0,False
5,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067923,ASS,Amsterdam Sloterdijk,2023-01-01T03:12:00+01:00,2.0,False,2023-01-01T03:12:00+01:00,2.0,False
6,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067924,ASD,Amsterdam Centraal,2023-01-01T03:18:00+01:00,1.0,False,2023-01-01T03:19:00+01:00,3.0,False
7,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067925,ASB,Amsterdam Bijlmer ArenA,2023-01-01T03:29:00+01:00,3.0,False,2023-01-01T03:30:00+01:00,3.0,False
8,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067926,UT,Utrecht Centraal,2023-01-01T03:47:00+01:00,2.0,False,NaN,NaN,NaN

In [18]:
test_unique = data[["Service_ID","Service:Train number","Service:Date"]].groupby("Service_ID").agg({
    'Service:Date' : pd.Series.nunique,
    'Service:Train number' : pd.Series.nunique
}).reset_index()

In [19]:
invalid_ids_dates = test_unique[(test_unique['Service:Date'] > 1)]
print(invalid_ids_dates)

Empty DataFrame
Columns: [Service_ID, Service:Date, Service:Train number]
Index: []

A single ID = a single date

In [20]:
invalid_ids_train = test_unique[(test_unique['Service:Train number'] > 1)]
invalid_ids_train

         Service_ID  Service:Date  Service:Train number
2256       10371795             1                     2
2295       10371854             1                     2
2308       10371877             1                     2
2356       10371951             1                     2
2359       10371955             1                     2
...             ...           ...                   ...
1421343    12694588             1                     2
1421346    12694629             1                     2
1421349    12694877             1                     2
1421351    12694916             1                     2
1421502    12703954             1                     2

[26883 rows x 3 columns]

But a single ID can refer to different trains

Which quantity does this represent?

In [21]:
print(invalid_ids_train['Service:Train number'].min())
print(invalid_ids_train['Service:Train number'].max())
print(len(test_unique[(test_unique['Service:Train number'] == 3)]))

2
3
1

In [22]:
len(test_unique[(test_unique['Service:Train number'] == 3)])

1

In [23]:
(len(invalid_ids_train)*2)/len(data['Service_ID'].unique())
#Less than 4% of trains

0.03782323970265359

Let's see a trip in detail:

In [24]:
data[data.Service_ID == 12694629]

,Service_ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled
21236999,12694629,2023-12-29,Sprinter,NS,308883,False,True,3,114345346,LEDN,Leiden Centraal,NaN,NaN,NaN,2023-12-29T21:53:00+01:00,0.0,True
21237000,12694629,2023-12-29,Sprinter,NS,308883,False,True,0,114345347,LDL,Leiden Lammenschans,2023-12-29T21:58:00+01:00,0.0,True,2023-12-29T21:58:00+01:00,0.0,True
21237001,12694629,2023-12-29,Sprinter,NS,308883,False,True,0,114345348,APN,Alphen a/d Rijn,2023-12-29T22:06:00+01:00,0.0,True,2023-12-29T22:09:00+01:00,0.0,True
21237002,12694629,2023-12-29,Sprinter,NS,308883,False,True,0,114345349,BDG,Bodegraven,2023-12-29T22:15:00+01:00,0.0,True,2023-12-29T22:16:00+01:00,0.0,True
21237003,12694629,2023-12-29,Sprinter,NS,308883,False,True,0,114345350,WD,Woerden,2023-12-29T22:23:00+01:00,0.0,True,2023-12-29T22:24:00+01:00,0.0,False
21237004,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345351,UT,Utrecht Centraal,2023-12-29T22:34:00+01:00,0.0,False,2023-12-29T22:36:00+01:00,3.0,False
21237005,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345352,UTVR,Utrecht Vaartsche Rijn,2023-12-29T22:38:00+01:00,3.0,False,2023-12-29T22:38:00+01:00,3.0,False
21237006,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345353,UTLN,Utrecht Lunetten,2023-12-29T22:41:00+01:00,3.0,False,2023-12-29T22:41:00+01:00,3.0,False
21237007,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345354,HTN,Houten,2023-12-29T22:44:00+01:00,3.0,False,2023-12-29T22:45:00+01:00,3.0,False
21237008,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345355,HTNC,Houten Castellum,2023-12-29T22:48:00+01:00,3.0,False,2023-12-29T22:48:00+01:00,3.0,False
21237009,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345356,CL,Culemborg,2023-12-29T22:54:00+01:00,2.0,False,2023-12-29T22:54:00+01:00,2.0,False
21237010,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345357,GDM,Geldermalsen,2023-12-29T23:00:00+01:00,2.0,False,2023-12-29T23:01:00+01:00,2.0,False
21237011,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345358,TPSW,Tiel Passewaaij,2023-12-29T23:08:00+01:00,1.0,False,2023-12-29T23:08:00+01:00,1.0,False
21237012,12694629,2023-12-29,Sprinter,NS,6785,False,True,0,114345359,TL,Tiel,2023-12-29T23:12:00+01:00,1.0,False,NaN,NaN,NaN

This one looks like a single train: Leiden to tiel = a route

In [25]:
data[data.Service_ID == 10371955]

,Service_ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled
40170,10371955,2023-01-02,Intercity,NS,2412,False,False,2,93109627,DDR,Dordrecht,NaN,NaN,NaN,2023-01-02T06:04:00+01:00,0.0,False
40171,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109628,RTB,Rotterdam Blaak,2023-01-02T06:15:00+01:00,1.0,False,2023-01-02T06:15:00+01:00,1.0,False
40172,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109629,RTD,Rotterdam Centraal,2023-01-02T06:18:00+01:00,1.0,False,2023-01-02T06:21:00+01:00,0.0,False
40173,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109630,SDM,Schiedam Centrum,2023-01-02T06:26:00+01:00,0.0,False,2023-01-02T06:26:00+01:00,0.0,False
40174,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109631,DT,Delft,2023-01-02T06:34:00+01:00,0.0,False,2023-01-02T06:34:00+01:00,0.0,False
40175,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109632,GV,Den Haag HS,2023-01-02T06:41:00+01:00,0.0,False,2023-01-02T06:43:00+01:00,0.0,False
40176,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109633,LAA,Den Haag Laan v NOI,2023-01-02T06:46:00+01:00,0.0,False,2023-01-02T06:46:00+01:00,0.0,False
40177,10371955,2023-01-02,Intercity,NS,2412,False,False,0,93109634,LEDN,Leiden Centraal,2023-01-02T06:55:00+01:00,0.0,False,2023-01-02T06:57:00+01:00,0.0,False
40178,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109635,SHL,Schiphol Airport,2023-01-02T07:12:00+01:00,0.0,False,2023-01-02T07:15:00+01:00,1.0,False
40179,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109636,ASDZ,Amsterdam Zuid,2023-01-02T07:21:00+01:00,1.0,False,2023-01-02T07:25:00+01:00,0.0,False
40180,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109637,ASB,Amsterdam Bijlmer ArenA,2023-01-02T07:31:00+01:00,0.0,False,2023-01-02T07:32:00+01:00,0.0,False
40181,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109638,UT,Utrecht Centraal,2023-01-02T07:48:00+01:00,0.0,False,2023-01-02T07:54:00+01:00,0.0,False
40182,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109639,HT,'s-Hertogenbosch,2023-01-02T08:22:00+01:00,0.0,False,2023-01-02T08:25:00+01:00,0.0,False
40183,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109640,EHV,Eindhoven Centraal,2023-01-02T08:43:00+01:00,1.0,False,2023-01-02T08:50:00+01:00,0.0,False
40184,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109641,HM,Helmond,2023-01-02T08:58:00+01:00,0.0,False,2023-01-02T08:58:00+01:00,2.0,False
40185,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109642,DN,Deurne,2023-01-02T09:06:00+01:00,2.0,False,2023-01-02T09:06:00+01:00,1.0,False
40186,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109643,HRT,Horst-Sevenum,2023-01-02T09:16:00+01:00,1.0,False,2023-01-02T09:17:00+01:00,0.0,False
40187,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109644,BR,Blerick,2023-01-02T09:25:00+01:00,0.0,False,2023-01-02T09:25:00+01:00,0.0,False
40188,10371955,2023-01-02,Intercity,NS,3523,False,False,0,93109645,VL,Venlo,2023-01-02T09:28:00+01:00,0.0,False,NaN,NaN,NaN

New question: is a single train ID always show a single status for cancellation?

In [26]:
test_status = data[["Service_ID","Service:Completely cancelled","Service:Partly cancelled"]].groupby("Service_ID").agg({
    'Service:Completely cancelled' : pd.Series.nunique,
    'Service:Partly cancelled' : pd.Series.nunique
}).reset_index()

In [27]:
invalid_ids_status = test_status[(test_status['Service:Completely cancelled'] > 1)]
print(invalid_ids_status)

Empty DataFrame
Columns: [Service_ID, Service:Completely cancelled, Service:Partly cancelled]
Index: []

In [28]:
invalid_ids_status = test_status[(test_status['Service:Partly cancelled'] > 1)]
print(invalid_ids_status)

Empty DataFrame
Columns: [Service_ID, Service:Completely cancelled, Service:Partly cancelled]
Index: []

Ok, so a single ID always has a single status

Does a partly cancelled train can have a fully cancelled status?

In [29]:
data_part_cancelled_trains_2023 = data[(data['Service:Partly cancelled'] == True)]
data_part_cancelled_trains_2023[(data_part_cancelled_trains_2023['Service:Completely cancelled'] == True)]

,Service_ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled
2294,10367968,2023-01-01,Intercity,NS,1827,True,True,0,93070433,LLS,Lelystad Centrum,NaN,NaN,NaN,2023-01-01T09:17:00+01:00,0.0,True
2295,10367968,2023-01-01,Intercity,NS,1827,True,True,0,93070434,ZL,Zwolle,2023-01-01T09:43:00+01:00,0.0,True,2023-01-01T09:48:00+01:00,0.0,True
2296,10367968,2023-01-01,Intercity,NS,1827,True,True,0,93070435,MP,Meppel,2023-01-01T10:03:00+01:00,0.0,True,2023-01-01T10:04:00+01:00,0.0,True
2297,10367968,2023-01-01,Intercity,NS,1827,True,True,0,93070436,SWK,Steenwijk,2023-01-01T10:13:00+01:00,0.0,True,2023-01-01T10:13:00+01:00,0.0,True
2298,10367968,2023-01-01,Intercity,NS,1827,True,True,0,93070437,HR,Heerenveen,2023-01-01T10:26:00+01:00,0.0,True,2023-01-01T10:26:00+01:00,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21239250,12700232,2023-12-30,Intercity,NS,302287,True,True,0,114401470,LEDN,Leiden Centraal,2023-12-30T23:15:00+01:00,0.0,True,2023-12-30T23:20:00+01:00,0.0,True
21239251,12700232,2023-12-30,Intercity,NS,302287,True,True,0,114401471,HAD,Heemstede-Aerdenhout,2023-12-30T23:34:00+01:00,0.0,True,2023-12-30T23:34:00+01:00,0.0,True
21239252,12700232,2023-12-30,Intercity,NS,302287,True,True,0,114401472,HLM,Haarlem,2023-12-30T23:39:00+01:00,0.0,True,2023-12-30T23:40:00+01:00,0.0,True
21239253,12700232,2023-12-30,Intercity,NS,302287,True,True,0,114401473,ASS,Amsterdam Sloterdijk,2023-12-30T23:49:00+01:00,0.0,True,2023-12-30T23:49:00+01:00,0.0,True
21239254,12700232,2023-12-30,Intercity,NS,302287,True,True,0,114401474,ASD,Amsterdam Centraal,2023-12-30T23:55:00+01:00,0.0,True,NaN,NaN,NaN

Yes it does. So I need to take that into account when counting number of partialy cancelled trains, and fully cancelled, so that a train cannot count twice

In [30]:
#Quickly check the dates of the data set:
print(data['Service:Date'].min())
print(data['Service:Date'].max())

2023-01-01
2023-12-31

Let's find the % of trains cancelled in 2023

## Cancellations rates:

In [31]:
total_trains_2023 = len(data['Service_ID'].unique())
total_trains_2023

1421507

In [32]:
data_full_cancelled_trains_2023 = data[(data['Service:Completely cancelled'] == True)]
full_cancelled_trains_2023 = len(data_full_cancelled_trains_2023['Service_ID'].unique())
full_cancelled_trains_2023

81091

In [33]:
data_full_cancelled_trains_2023[(data_full_cancelled_trains_2023['Service:Partly cancelled'] == False)]

,Service_ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled
392390,10408009,2023-01-05,Intercity,NS,102454,True,False,0,93465170,HFD,Hoofddorp,NaN,NaN,NaN,2023-01-05T17:39:00+01:00,0.0,False
392391,10408009,2023-01-05,Intercity,NS,102454,True,False,0,93465171,SHL,Schiphol Airport,2023-01-05T17:42:00+01:00,0.0,False,NaN,NaN,NaN
458215,10414674,2023-01-07,Extra trein,NS,29000,True,False,0,93530999,AC,Abcoude,NaN,NaN,NaN,2023-01-07T05:42:00+01:00,0.0,False
458216,10414674,2023-01-07,Extra trein,NS,29000,True,False,0,93538488,ASDM,Amsterdam Muiderpoort,2023-01-07T05:56:00+01:00,0.0,False,2023-01-07T05:56:00+01:00,0.0,False
458217,10414674,2023-01-07,Extra trein,NS,29000,True,False,0,93531000,ASD,Amsterdam Centraal,2023-01-07T06:01:00+01:00,0.0,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21236619,12693819,2023-12-29,Sprinter,NS,209065,True,False,0,114337228,WV,Wolvega,2023-12-29T19:28:00+01:00,0.0,False,NaN,NaN,NaN
21237543,12698068,2023-12-30,Extra trein,NS,29230,True,False,0,114379412,TBU,Tilburg Universiteit,NaN,NaN,NaN,2023-12-30T13:48:00+01:00,13.0,False
21237544,12698068,2023-12-30,Extra trein,NS,29230,True,False,0,114379508,TB,Tilburg,2023-12-30T13:49:00+01:00,7.0,False,2023-12-30T13:49:00+01:00,0.0,True
21237545,12698068,2023-12-30,Extra trein,NS,29230,True,False,0,114380148,HT,'s-Hertogenbosch,2023-12-30T14:00:00+01:00,14.0,False,NaN,NaN,NaN
21237546,12698068,2023-12-30,Extra trein,NS,29230,True,False,0,114379413,BTL,Boxtel,2023-12-30T13:59:00+01:00,6.0,False,NaN,NaN,NaN

In [34]:
data_part_cancelled_trains_2023 = data[(data['Service:Completely cancelled'] == False)&(data['Service:Partly cancelled'] == True)]
#to not count twice trains that have both status
part_cancelled_trains_2023 = len(data_part_cancelled_trains_2023['Service_ID'].unique())
part_cancelled_trains_2023

86623

I will apply the same logic as cancellations from Avanti and GWR : partly cancelled trains count 0.5

In [35]:
#% of fully cancelled trains: 
full_cancelled_trains_2023/total_trains_2023

0.05704579717159325

In [36]:
cancellation_rate_2023_all_trains = (full_cancelled_trains_2023 + (part_cancelled_trains_2023*0.5))/total_trains_2023
cancellation_rate_2023_all_trains

0.08751451804317531

Now let's check per train type

In [37]:
data['Service:Type'].unique()

array(['Intercity', 'Sprinter', 'Intercity direct', 'Speciale Trein',
       'Stopbus i.p.v. trein', 'Snelbus i.p.v. trein', 'Thalys',
       'Extra trein', 'Metro i.p.v. trein', 'Stopbus ipv trein',
       'Snelbus ipv trein', 'Metro ipv trein'], dtype=object)

<b>Inforation found on NS website: </b>
<i>NS has 2 different types of trains: Sprinter and Intercity. The Sprinter is ideal for shorter journeys and stops at every station along the route. It has many wide doors to facilitate quick boarding and unboarding. The facilities in these trains are geared towards short travel times.</i>

--> We should target only Intercity and Intercity direct trains

In [38]:
data_Intercity_2023 = data[(data['Service:Type'] == 'Intercity')|(data['Service:Type'] == 'Intercity direct')]
total_Intercity_2023 = len(data_Intercity_2023['Service_ID'].unique())
total_Intercity_2023

504082

In [39]:
data_full_cancelled_Intercity_2023 = data_Intercity_2023[(data_Intercity_2023['Service:Completely cancelled'] == True)]
full_cancelled_Intercity_2023 = len(data_full_cancelled_Intercity_2023['Service_ID'].unique())
full_cancelled_Intercity_2023

11861

In [40]:
data_part_cancelled_Intercity_2023 = data_Intercity_2023[(data_Intercity_2023['Service:Completely cancelled'] == False)&(data_Intercity_2023['Service:Partly cancelled'] == True)]
#to not count twice Intercity that have both status
part_cancelled_Intercity_2023 = len(data_part_cancelled_Intercity_2023['Service_ID'].unique())
part_cancelled_Intercity_2023

51112

In [41]:
cancellation_rate_2023_Intercity = (full_cancelled_Intercity_2023 + (part_cancelled_Intercity_2023*0.5))/total_Intercity_2023
print(f'In 2023 {round(cancellation_rate_2023_Intercity*100,2)}% Of Intercity trains were cancelled or partly cancelled')

In 2023 7.42% Of Intercity trains were cancelled or partly cancelled

## Delays rate

For delays, we want nb of trains delays > 5 min at the terminus.
But how to identify the terminus in this dataset? It is always the last line of the Service_ID.

In [42]:
#Step 1: subset data with no cancellations (nor full, nor partial): 

intercity_wo_cancel = data_Intercity_2023[(data_Intercity_2023['Service:Completely cancelled'] == False)&(data_Intercity_2023['Service:Partly cancelled'] == False)]
len(intercity_wo_cancel['Service_ID'].unique())

441109

In [43]:
#Step 2: add a new index
delays_intercity_2023 = intercity_wo_cancel
delays_intercity_2023['Index'] = range(1, len(delays_intercity_2023) + 1)
delays_intercity_2023.head(5)

C:\Users\TE\AppData\Local\Temp\ipykernel_15056\3056194036.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  delays_intercity_2023['Index'] = range(1, len(delays_intercity_2023) + 1)

,Service_ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Index
0,10367702,2023-01-01,Intercity,NS,1410,False,False,3,93067918,RTD,Rotterdam Centraal,NaN,NaN,NaN,2023-01-01T02:00:00+01:00,1.0,False,1
1,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067919,DT,Delft,2023-01-01T02:13:00+01:00,0.0,False,2023-01-01T02:13:00+01:00,0.0,False,2
2,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067920,GV,Den Haag HS,2023-01-01T02:21:00+01:00,0.0,False,2023-01-01T02:22:00+01:00,0.0,False,3
3,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067921,LEDN,Leiden Centraal,2023-01-01T02:35:00+01:00,0.0,False,2023-01-01T02:40:00+01:00,0.0,False,4
4,10367702,2023-01-01,Intercity,NS,1410,False,False,0,93067922,SHL,Schiphol Airport,2023-01-01T02:56:00+01:00,0.0,False,2023-01-01T03:03:00+01:00,0.0,False,5

In [58]:
#the filtering #3 should not be here, but after step #4

In [44]:
#4 for each Service_ID select the maximum index, to have only the terminus
delays_terminus_intercity_2023 = []
unique_Service_ID = delays_intercity_2023['Service_ID'].unique()

for Id in unique_Service_ID: 
    subset_temp = delays_intercity_2023[delays_intercity_2023['Service_ID'] == Id]
    delay_terminus = subset_temp[subset_temp['Index'] == max(subset_temp['Index'])]
    delays_terminus_intercity_2023.append(delay_terminus)

In [47]:
delays_terminus_intercity_2023 = pd.concat(delays_terminus_intercity_2023, ignore_index=True)

In [48]:
#3 To lighten the dataset, already get rid off travel with no delays
delays_terminus_intercity_2023 = delays_terminus_intercity_2023[delays_terminus_intercity_2023["Stop:Arrival delay"] > 5]

In [49]:
delays_terminus_intercity_2023_5min = delays_terminus_intercity_2023[delays_terminus_intercity_2023['Stop:Arrival delay'] > 5]
delays_terminus_intercity_2023_10min = delays_terminus_intercity_2023[delays_terminus_intercity_2023['Stop:Arrival delay'] > 10]
delays_terminus_intercity_2023_15min = delays_terminus_intercity_2023[delays_terminus_intercity_2023['Stop:Arrival delay'] > 15]

In [50]:
nb_Intercity_running_2023 = total_Intercity_2023 - full_cancelled_Intercity_2023 - part_cancelled_Intercity_2023

In [51]:
punctual_terminus_intercity_2023_5min = nb_Intercity_running_2023 - len(delays_terminus_intercity_2023_5min)
punctual_terminus_intercity_2023_10min = nb_Intercity_running_2023 - len(delays_terminus_intercity_2023_10min)
punctual_terminus_intercity_2023_15min = nb_Intercity_running_2023 - len(delays_terminus_intercity_2023_15min)

In [52]:
punctuality_rate_5min = (punctual_terminus_intercity_2023_5min/nb_Intercity_running_2023)*100
punctuality_rate_10min = (punctual_terminus_intercity_2023_10min/nb_Intercity_running_2023)*100
punctuality_rate_15min = (punctual_terminus_intercity_2023_15min/nb_Intercity_running_2023)*100
punctuality_rate_5min

92.50480040080797

In [53]:
(total_Intercity_2023 - len(delays_terminus_intercity_2023_5min))/total_Intercity_2023

0.9344114648013617

In [54]:
print(f'In 2023, their were {nb_Intercity_running_2023} Intercity trains running')
print(f'Among which {round(punctuality_rate_5min,2)}% were punctual (delay < 5 min)')

In 2023, their were 441109 Intercity trains running
Among which 92.5% were punctual (delay < 5 min)

# Summary:

In [67]:
print('In 2023:')
print(f'{total_Intercity_2023} Intercity and Intercity direct trains were planed. Among these trains, the cancellation rate was {round(cancellation_rate_2023_Intercity*100,2)}% *')
print(f'On the {nb_Intercity_running_2023} trains running, {round(punctuality_rate_5min,2)}% were punctual (delay < 5 min)')
print('')
print('*: Cancellation rate is the % of trains fully cancelled + half of the percentage of partially cancelled trains')

In 2023:
504082 Intercity and Intercity direct trains were planed. Among these trains, the cancellation rate was 7.42% *
On the 441109 trains running, 87.71% were punctual (delay < 5 min)

*: Cancellation rate is the % of trains fully cancelled + half of the percentage of partially cancelled trains

To go further:

In [68]:
print(f'The punctuality rate at 10 min was:{round(punctuality_rate_10min)}%')
print(f'The punctuality rate at 15 min was:{round(punctuality_rate_15min)}%')

The punctuality rate at 10 min was:97%
The punctuality rate at 15 min was:99%